services:
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    networks:
      - web
    ports:
      - "5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  php:
    build: .
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    networks:
      - web
    volumes:
      - caddy_data:/data
      - caddy_config:/config

networks:
  web:

volumes:
  caddy_data:
  caddy_config:
  database_data: