parameters:
    admin_email: "%env(string:default:default_admin_email:ADMIN_EMAIL)%"
    default_admin_email: admin@example.com

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'